# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48e852504ea6cfd62d6182d57a1eafce070bcb073acb2e86f5ca95734af36bd162e0a7ca4e2d14a4f1a79cd722ba3aaadeb7c2469d8ab93f2ab3ca33c01fdadf

test:
  secret_key_base: de4022e6cfed6717edfd941a207018352141637f79ee6ae197b239fbadf8a9e3539d2f8b3385266dabceb75ddff2810bfae672d9f1123ef0b90ff9a0716b88ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
